[tool.poetry]
name = "eciespy"
version = "0.3.5"
packages = [
    { include = "ecies" },
]
license = "MIT"
description = "Elliptic Curve Integrated Encryption Scheme for secp256k1 in Python"
authors = ["Weiliang Li <to.be.impressive@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/ecies/py"
repository = "https://github.com/ecies/py"
documentation = "https://github.com/ecies/py"

[tool.poetry.dependencies]
python = "^3.5.3"
coincurve = "^13.0"
pycryptodome = "^3.9"
eth-keys = "^0.3.3"

[tool.poetry.dev-dependencies]
ipython = { version = "^7.15", python = "^3.6" }
mypy = "^0.770"
flake8 = "^3.8"
black = { version = "^19.10b0", python = "^3.6" }
