version: 2

jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            venv/bin/pip install -U pip
            venv/bin/pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pip install codecov codacy-coverage
            coverage run -m doctest -v ecies/utils.py
            coverage run -m unittest discover .
            codecov
            python-codacy-coverage -r coverage.xml

      - persist_to_workspace:
          root: ~/repo
          paths: .

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = kigawas" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            python setup.py sdist
            python setup.py bdist_wheel
            twine upload dist/*

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - deploy:
          requires:
            - test-3.7
            - test-3.6
            - test-3.5
