name: CI

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - run: brew install automake
        if: matrix.os == 'macos-latest'

      - run: poetry install

      - name: Run test
        run: poetry run pytest -s --cov=ecies tests --cov-report xml

      - run: ./scripts/ci.sh

      - uses: codecov/codecov-action@v4

      - run: poetry build
